env:
  node: true
  es2021: true
  jest: true
extends:
  - airbnb-base
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
root: true
# ignorePatterns: 
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: 'tsconfig.json'
plugins:
  - '@typescript-eslint'
rules: {}
